### ISSUE TITLE
B field does not line up with gyromotion

### ISSUE THREAD

**Issue by dlg0** [ORNL-Fusion/gimp#1]
@tyounkin 

In the final plot of the orbits, the B field vector is not the axis around which the gyro motion happens. I assume this is just an axis ordering issue, but needs to be fixed.

**Comment by tyounkin** [comment]
This was occurring because of a mistake in the gimpInterpVector1D function. The function was interpolating the same component of the field three times. This has been fixed and pushed to the repository in the changes on Monday January 11, 2016.
