### ISSUE TITLE
Implement "previous" particle properties

### ISSUE THREAD

**Issue by dlg0** [ORNL-Fusion/gimp#2]
@tyounkin 

At present we have not implemented the p.xPrevious type variables in the move / operators. Doing this will give us a way around the NaN issue.

**Comment by tyounkin** [comment]
The p.xPrevious and p.vxPrevious variables are now updated once per time step, i.e. the "previous" properties are not update after each individual operator (Crossfield diffusion, coulomb collisions, boris move). The update is very simple: If the particles has not intersected the surface or exited the volume, then update the "previous" properties before going on to operate on the particle for the next time step.
